version: '3.8'

services:
  v1:
    build: ./v1
    container_name: app_v1

  v2:
    build: ./v2
    container_name: app_v2

  nginx:
    image: nginx:latest
    container_name: nginx_canary
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - v1
      - v2